/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalexam_buianhtruc_5149;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class AppHinh extends javax.swing.JFrame {
    FormLK lk=new FormLK();
    DSHinh danhSach=new DSHinh();
    DefaultTableModel table= new DefaultTableModel();
    public AppHinh() {
        initComponents();
        table.setColumnIdentifiers(new Object[]{"STT", "Loại hình", "Bán kính", "Cạnh a",
            "Cạnh b", "Cạnh c", "Diện tích"});
        jTable.setModel(table);
        CheckTT();
    }
    
    void CheckTT()
    {
        if(!danhSach.CheckDL())
        {
            btGhifile.setEnabled(false);
            btMax.setEnabled(false);
            btLietke.setEnabled(false);
        }
        else
        {
            btGhifile.setEnabled(true);
            btMax.setEnabled(true);
            btLietke.setEnabled(true);
        }
        if(cbLoaihinh.getSelectedIndex()==0)
        {
            tfBankinh.setEnabled(true);
            tfCanha.setEnabled(false);
            tfCanhb.setEnabled(false);
            tfCanhh.setEnabled(false);
            if(tfBankinh.getText().equals("")) btThemmoi.setEnabled(false);
            else btThemmoi.setEnabled(true);
        }
        if(cbLoaihinh.getSelectedIndex()==1)
        {
            tfBankinh.setEnabled(false);
            tfCanha.setEnabled(true);
            tfCanhb.setEnabled(true);
            tfCanhh.setEnabled(false);
            if(tfCanha.getText().equals("") || tfCanhb.getText().equals("")) btThemmoi.setEnabled(false);
            else btThemmoi.setEnabled(true);
        }
        if(cbLoaihinh.getSelectedIndex()==2)
        {
            tfBankinh.setEnabled(false);
            tfCanha.setEnabled(true);
            tfCanhb.setEnabled(true);
            tfCanhh.setEnabled(true);
            if(tfCanha.getText().equals("") || tfCanhb.getText().equals("") || tfCanhh.getText().equals("")) btThemmoi.setEnabled(false);
            else btThemmoi.setEnabled(true);
        }
        
    }
    
    void NapDL()
    {
        int STT = 1;
        if (danhSach.CheckDL() == false) {
            JOptionPane.showMessageDialog(rootPane, "Khong co du lieu!!!");
            return;
        }
        table.setRowCount(0);
        for (IHinh i : danhSach.getDanhSach()) {
            String loai="";
            if(i instanceof HinhTron)
            {
                loai="Tròn";
                table.addRow(new Object[]{STT, loai, ((HinhTron)i).getR(), "", "",
                "", i.DienTich()});
            }
            else if(i instanceof HinhCN)
            {
                loai="Chữ nhật";
                table.addRow(new Object[]{STT, loai, "", ((HinhCN)i).getA(), ((HinhCN)i).getB(),
                "", i.DienTich()});
            }
            else 
            {
                loai="Hộp chữ nhật";
                table.addRow(new Object[]{STT, loai, "", ((HinhHCN)i).getA(), ((HinhHCN)i).getB(),
                ((HinhHCN)i).getH(), i.DienTich()});
            }
            
            STT++;
        }
        CheckTT();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfBankinh = new javax.swing.JTextField();
        tfCanha = new javax.swing.JTextField();
        tfCanhb = new javax.swing.JTextField();
        tfCanhh = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        cbLoaihinh = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btDocfile = new javax.swing.JButton();
        btGhifile = new javax.swing.JButton();
        btMoi = new javax.swing.JButton();
        btThemmoi = new javax.swing.JButton();
        btMax = new javax.swing.JButton();
        btLietke = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HÌNH");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Loại hình:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Bán kính:");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Cạnh a:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Cạnh b:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cạnh h:");

        tfBankinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfBankinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBankinhKeyReleased(evt);
            }
        });

        tfCanha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCanha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCanhaKeyReleased(evt);
            }
        });

        tfCanhb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCanhb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCanhbKeyReleased(evt);
            }
        });

        tfCanhh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfCanhh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCanhhKeyReleased(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        cbLoaihinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLoaihinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tròn", "Chữ nhật", "Hộp Chữ Nhật" }));
        cbLoaihinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLoaihinhActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("NHẬP THÔNG TIN");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("THÔNG TIN");

        btDocfile.setText("Đọc file");
        btDocfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocfileActionPerformed(evt);
            }
        });

        btGhifile.setText("Ghi file");
        btGhifile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGhifileActionPerformed(evt);
            }
        });

        btMoi.setText("Mới");
        btMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoiActionPerformed(evt);
            }
        });

        btThemmoi.setText("Thêm mới");
        btThemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemmoiActionPerformed(evt);
            }
        });

        btMax.setText("Thông tin hình chữ nhật lớn nhất");
        btMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMaxActionPerformed(evt);
            }
        });

        btLietke.setText("Liệt kê các hình tăng dần theo diện tích");
        btLietke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLietkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfBankinh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCanha, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCanhb, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfCanhh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbLoaihinh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btGhifile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btDocfile))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btThemmoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btLietke, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbLoaihinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfBankinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfCanha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfCanhb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfCanhh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDocfile)
                            .addComponent(btMoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btGhifile)
                            .addComponent(btThemmoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btMax)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btLietke)
                        .addGap(0, 34, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbLoaihinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLoaihinhActionPerformed
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_cbLoaihinhActionPerformed

    private void btDocfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocfileActionPerformed
        // TODO add your handling code here:
        JFileChooser open =new JFileChooser();
            open.showOpenDialog(null);
            String path="";
            path=open.getSelectedFile().getPath();
            if(!path.equals("")) 
            {
                danhSach.readfile(path);
                NapDL();
            }
    }//GEN-LAST:event_btDocfileActionPerformed

    private void btGhifileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGhifileActionPerformed
        // TODO add your handling code here:
        JFileChooser open =new JFileChooser();
            open.showSaveDialog(null);
            String path="";
            path=open.getSelectedFile().getPath();
            if(!path.equals("")) danhSach.wirtefile(path);
    }//GEN-LAST:event_btGhifileActionPerformed

    private void btMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoiActionPerformed
        // TODO add your handling code here:
        cbLoaihinh.setSelectedIndex(0);
        tfBankinh.setText("");
        tfCanha.setText("");
        tfCanhb.setText("");
        tfCanhh.setText("");
        CheckTT();
    }//GEN-LAST:event_btMoiActionPerformed

    private void tfBankinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBankinhKeyReleased
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_tfBankinhKeyReleased

    private void tfCanhaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCanhaKeyReleased
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_tfCanhaKeyReleased

    private void tfCanhbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCanhbKeyReleased
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_tfCanhbKeyReleased

    private void tfCanhhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCanhhKeyReleased
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_tfCanhhKeyReleased

    private void btMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMaxActionPerformed
        // TODO add your handling code here:
        IHinh temp=danhSach.FindMax();
        JOptionPane.showMessageDialog(rootPane, "Hình chữ nhật có:\nCạnh a= "+((HinhCN)temp).getA()
                                      +"\nCạnh b= "+((HinhCN)temp).getB()
                                      +"\nCó diện tích lớn nhất S= "+temp.DienTich());
    }//GEN-LAST:event_btMaxActionPerformed

    private void btLietkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLietkeActionPerformed
        // TODO add your handling code here:
        lk.NapDL(danhSach);
        lk.setVisible(true);
    }//GEN-LAST:event_btLietkeActionPerformed

    private void btThemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemmoiActionPerformed
        // TODO add your handling code here:
        try
        {
            if(cbLoaihinh.getSelectedIndex()==0)
            {
                danhSach.ThemMoi(new HinhTron(Double.parseDouble(tfBankinh.getText())));
            }
            if(cbLoaihinh.getSelectedIndex()==1)
            {
                danhSach.ThemMoi(new HinhCN(Double.parseDouble(tfCanha.getText()),Double.parseDouble(tfCanhb.getText())));
            }
            if(cbLoaihinh.getSelectedIndex()==2)
            {
                danhSach.ThemMoi(new HinhHCN(Double.parseDouble(tfCanha.getText()),Double.parseDouble(tfCanhb.getText()),
                                             Double.parseDouble(tfCanhb.getText())));
            }
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e,"!!!WARNING!!!",JOptionPane.WARNING_MESSAGE);
        }
        NapDL();
    }//GEN-LAST:event_btThemmoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppHinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppHinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDocfile;
    private javax.swing.JButton btGhifile;
    private javax.swing.JButton btLietke;
    private javax.swing.JButton btMax;
    private javax.swing.JButton btMoi;
    private javax.swing.JButton btThemmoi;
    private javax.swing.JComboBox<String> cbLoaihinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField tfBankinh;
    private javax.swing.JTextField tfCanha;
    private javax.swing.JTextField tfCanhb;
    private javax.swing.JTextField tfCanhh;
    // End of variables declaration//GEN-END:variables
}
