/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalexam_buianhtruc_5149;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trucn
 */
public class FormLK extends javax.swing.JFrame {

    DefaultTableModel table= new DefaultTableModel();
    DSHinh danhSach=new DSHinh();
    public FormLK() {
        initComponents();
    }
    void NapDL(DSHinh ds)
    {
        danhSach=ds;
        int STT=1;
        table= new DefaultTableModel();
        table.setColumnIdentifiers(new Object[]{"STT", "Loại hình", "Bán kính", "Cạnh a",
            "Cạnh b", "Cạnh c", "Diện tích"});
        jTable.setModel(table);
        table.setRowCount(0);
        for (IHinh i : danhSach.SapXepTang()) {
            String loai="";
            if(i instanceof HinhTron)
            {
                loai="Tròn";
                table.addRow(new Object[]{STT, loai, ((HinhTron)i).getR(), "", "",
                "", i.DienTich()});
            }
            else if(i instanceof HinhCN)
            {
                loai="Chữ nhật";
                table.addRow(new Object[]{STT, loai, "", ((HinhCN)i).getA(), ((HinhCN)i).getB(),
                "", i.DienTich()});
            }
            else 
            {
                loai="Hộp chữ nhật";
                table.addRow(new Object[]{STT, loai, "", ((HinhHCN)i).getA(), ((HinhHCN)i).getB(),
                ((HinhHCN)i).getH(), i.DienTich()});
            }
            
            STT++;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LIET KE");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LIỆT KÊ TĂNG DẦN THEO DIỆN TÍCH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
}
