/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package th14;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trucn
 */
public class AppBac2 extends javax.swing.JFrame {
    private PhuongTrinhBac2 bac2=new PhuongTrinhBac2();
    private DefaultTableModel table=new DefaultTableModel();
    /**
     * Creates new form AppBac2
     */
    public AppBac2() {
        initComponents();
         btGai.setEnabled(false);
         btLamLai.setEnabled(false);
         table.setColumnIdentifiers(new Object[]{"A","B","C","Mghiệm"});
         jTable.setModel(table);
         btAdd.setEnabled(false);
         tfA.setFocusCycleRoot(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbA = new javax.swing.JLabel();
        lbB = new javax.swing.JLabel();
        lbC = new javax.swing.JLabel();
        tfA = new javax.swing.JTextField();
        tfB = new javax.swing.JTextField();
        tfC = new javax.swing.JTextField();
        lbKQ = new javax.swing.JLabel();
        btGai = new javax.swing.JButton();
        btLamLai = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ax^2 + Bx  + C");
        setName(""); // NOI18N

        lbA.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbA.setText("A");

        lbB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbB.setText("B");

        lbC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbC.setText("C");

        tfA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAActionPerformed(evt);
            }
        });
        tfA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfAKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfAKeyReleased(evt);
            }
        });

        tfB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBActionPerformed(evt);
            }
        });
        tfB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfBKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBKeyReleased(evt);
            }
        });

        tfC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCActionPerformed(evt);
            }
        });
        tfC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfCKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCKeyReleased(evt);
            }
        });

        lbKQ.setText("Kết Quả:");

        btGai.setText("Giải");
        btGai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGaiActionPerformed(evt);
            }
        });

        btLamLai.setText("Làm Lại");
        btLamLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamLaiActionPerformed(evt);
            }
        });

        btThoat.setText("Thoát");
        btThoat.setName(""); // NOI18N
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        btAdd.setText("Add");
        btAdd.setName(""); // NOI18N
        btAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btGai)
                        .addGap(18, 18, 18)
                        .addComponent(btLamLai)
                        .addGap(18, 18, 18)
                        .addComponent(btThoat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbC, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfC, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbB, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbA, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfA, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbKQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAdd)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbA, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(lbKQ, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btGai)
                            .addComponent(btLamLai)
                            .addComponent(btThoat)
                            .addComponent(btAdd))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGaiActionPerformed

        bac2.setB(Double.parseDouble(tfB.getText()));
        bac2.setA(Double.parseDouble(tfA.getText()));
        bac2.setC(Double.parseDouble(tfC.getText()));
        lbKQ.setText("Kết quả:"+bac2.Giai());
        btGai.setEnabled(false);
        btAdd.setEnabled(true);
    }//GEN-LAST:event_btGaiActionPerformed

    private void tfCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCActionPerformed
        check();   
    }//GEN-LAST:event_tfCActionPerformed

    private void tfAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAActionPerformed
        check();
    }//GEN-LAST:event_tfAActionPerformed

    private void tfBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBActionPerformed
        check();
    }//GEN-LAST:event_tfBActionPerformed

    private void btLamLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamLaiActionPerformed
        tfA.setText("");
        tfB.setText("");
        tfC.setText("");
        lbKQ.setText("Kết quả:");
        tfA.requestFocus();
        check();
        btAdd.setEnabled(false);
    }//GEN-LAST:event_btLamLaiActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void tfAKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfAKeyPressed

    private void tfBKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tfBKeyPressed

    private void tfCKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfCKeyPressed

    private void tfAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAKeyReleased
        // TODO add your handling code here:
        check();
    }//GEN-LAST:event_tfAKeyReleased

    private void tfBKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBKeyReleased
        // TODO add your handling code here:
        check();
    }//GEN-LAST:event_tfBKeyReleased

    private void tfCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCKeyReleased
        // TODO add your handling code here:\
        check();
    }//GEN-LAST:event_tfCKeyReleased

    private void btAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddActionPerformed
        // TODO add your handling code here:
        table.addRow(new Object[] {bac2.getA(),bac2.getB(),bac2.getC(),bac2.Giai()});
        btAdd.setEnabled(false);
                
    }//GEN-LAST:event_btAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppBac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppBac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppBac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppBac2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppBac2().setVisible(true);
            }
        });
    }
    
    public void check()
    {
        if(tfA.getText().equals("") || tfB.getText().equals("")|| tfC.getText().equals(""))
        {
            btGai.setEnabled(false);
            btLamLai.setEnabled(false);
            
        }
        else 
        {
            btGai.setEnabled(true);
            btLamLai.setEnabled(true);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btGai;
    private javax.swing.JButton btLamLai;
    private javax.swing.JButton btThoat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JLabel lbA;
    private javax.swing.JLabel lbB;
    private javax.swing.JLabel lbC;
    private javax.swing.JLabel lbKQ;
    private javax.swing.JTextField tfA;
    private javax.swing.JTextField tfB;
    private javax.swing.JTextField tfC;
    // End of variables declaration//GEN-END:variables
}
