/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlybenhvien;

import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trucn
 */
public class AppBenhVien extends javax.swing.JFrame {
    FormTong tong=new FormTong();
    
    DSBENHNHAN danhsachBN = new DSBENHNHAN();
    DSNHANVIEN danhsachNV = new DSNHANVIEN();
    DefaultTableModel tableBN = new DefaultTableModel();
    DefaultTableModel tableNV = new DefaultTableModel();
    private int localbn,localnv,modeBN,modeNV;


    public AppBenhVien() {
        initComponents();
        tableBN.setColumnIdentifiers(new Object[]{"STT", "Mã", "Tên Bệnh Nhân", "Phòng yêu cầu", "Ngày nhập viện",
            "Ngày xuất viện", "Loại bảo hiểm", "Viện phí"});
        jTable.setModel(tableBN);
        tableNV.setColumnIdentifiers(new Object[]{"STT", "Mã", "Tên Bệnh Nhân", "Giới tính", "Ngày ký hợp đồng",
            "Mức thưởng", "Chức vụ", "Tiền lương"});
        jTable1.setModel(tableNV);
        danhsachBN.readfile("BN.txt");
        danhsachBN.SapXepMacDinh();
        danhsachNV.readfile("NV.txt");
        danhsachNV.SapXepMacDinh();
        modeBN=0;
        modeNV=0;
        btMacdinh.setEnabled(false);
        btMacdinh1.setEnabled(false);
        ModeBN(modeBN);
        ModeNV(modeNV);
        if (danhsachBN.CheckDL()) {
            HienThiBN(1);
        }
        if (danhsachNV.CheckDL()) {
            HienThiNV(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfMa = new javax.swing.JTextField();
        tfTen = new javax.swing.JTextField();
        tfNgayxuat = new javax.swing.JTextField();
        tfNgaynhap = new javax.swing.JTextField();
        rbCo = new javax.swing.JRadioButton();
        rbKhong = new javax.swing.JRadioButton();
        rbBHYT = new javax.swing.JRadioButton();
        rbBHXH = new javax.swing.JRadioButton();
        btThem = new javax.swing.JButton();
        btTimkiem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btXuatfile = new javax.swing.JButton();
        btMoi = new javax.swing.JButton();
        btDocfile = new javax.swing.JButton();
        btTong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        btDau = new javax.swing.JButton();
        btLui = new javax.swing.JButton();
        btCuoi = new javax.swing.JButton();
        btTien = new javax.swing.JButton();
        tfSTT = new javax.swing.JTextField();
        btAbout = new javax.swing.JButton();
        btGiam = new javax.swing.JButton();
        btTang = new javax.swing.JButton();
        btThoat = new javax.swing.JButton();
        btCapnhat = new javax.swing.JButton();
        btMacdinh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfMa1 = new javax.swing.JTextField();
        tfTen1 = new javax.swing.JTextField();
        tfMucthuong = new javax.swing.JTextField();
        tfNgayKHD = new javax.swing.JTextField();
        rbNam = new javax.swing.JRadioButton();
        rbNu = new javax.swing.JRadioButton();
        btThem1 = new javax.swing.JButton();
        btTimkiem1 = new javax.swing.JButton();
        btXoa1 = new javax.swing.JButton();
        btXuatfile1 = new javax.swing.JButton();
        btMoi1 = new javax.swing.JButton();
        btDocfile1 = new javax.swing.JButton();
        btTong1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btDau1 = new javax.swing.JButton();
        btLui1 = new javax.swing.JButton();
        btCuoi1 = new javax.swing.JButton();
        btTien1 = new javax.swing.JButton();
        tfSTT1 = new javax.swing.JTextField();
        btAbout1 = new javax.swing.JButton();
        btGiam1 = new javax.swing.JButton();
        btTang1 = new javax.swing.JButton();
        btThoat1 = new javax.swing.JButton();
        btCapnhat1 = new javax.swing.JButton();
        btMacdinh1 = new javax.swing.JButton();
        cbChucvu = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ BỆNH VIỆN");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("THÔNG TIN BỆNH NHÂN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BẢNG THỐNG KÊ BỆNH NHÂN");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mã bệnh nhân:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tên bệnh nhân:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ngày nhập viện:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Ngày xuất viện:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Phòng theo yêu cầu:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Loại bảo hiểm:");

        tfMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMaKeyReleased(evt);
            }
        });

        tfTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenActionPerformed(evt);
            }
        });
        tfTen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTenKeyReleased(evt);
            }
        });

        tfNgayxuat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNgayxuatKeyReleased(evt);
            }
        });

        tfNgaynhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNgaynhapKeyReleased(evt);
            }
        });

        buttonGroup1.add(rbCo);
        rbCo.setSelected(true);
        rbCo.setText("Có");
        rbCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbKhong);
        rbKhong.setText("Không");

        buttonGroup2.add(rbBHYT);
        rbBHYT.setText("BHYT");
        rbBHYT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBHYTActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbBHXH);
        rbBHXH.setSelected(true);
        rbBHXH.setText("BHXH");

        btThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btThem.setLabel("Thêm");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btTimkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTimkiem.setLabel("Tìm Kiếm");
        btTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimkiemActionPerformed(evt);
            }
        });

        btXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btXoa.setLabel("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btXuatfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btXuatfile.setText("Xuất file");
        btXuatfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXuatfileActionPerformed(evt);
            }
        });

        btMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btMoi.setText("Mới");
        btMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoiActionPerformed(evt);
            }
        });

        btDocfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btDocfile.setText("Đọc file");
        btDocfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocfileActionPerformed(evt);
            }
        });

        btTong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTong.setText("Tổng tiền theo loại bệnh nhân");
        btTong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTongActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        btDau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btDau.setText("Đầu");
        btDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDauActionPerformed(evt);
            }
        });

        btLui.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btLui.setText("Lùi");
        btLui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLuiActionPerformed(evt);
            }
        });

        btCuoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCuoi.setText("Cuối");
        btCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCuoiActionPerformed(evt);
            }
        });

        btTien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTien.setText("Tiến");
        btTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTienActionPerformed(evt);
            }
        });

        tfSTT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfSTT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSTTActionPerformed(evt);
            }
        });
        tfSTT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSTTKeyReleased(evt);
            }
        });

        btAbout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAbout.setText("About");
        btAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAboutActionPerformed(evt);
            }
        });

        btGiam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btGiam.setText("Giảm");
        btGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGiamActionPerformed(evt);
            }
        });

        btTang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTang.setText("Tăng");
        btTang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTangActionPerformed(evt);
            }
        });

        btThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btThoat.setText("Thoát");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        btCapnhat.setText("Cập nhật");
        btCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapnhatActionPerformed(evt);
            }
        });

        btMacdinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btMacdinh.setText("Mặc định");
        btMacdinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMacdinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1037, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(53, 53, 53)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(btDau, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btLui, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfSTT, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btTien, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btCuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(10, 10, 10)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rbCo)
                                                        .addComponent(rbBHYT))
                                                    .addGap(38, 38, 38)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rbBHXH)
                                                        .addComponent(rbKhong)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(tfNgayxuat, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfNgaynhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(tfMa, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(85, 85, 85)
                                                    .addComponent(btCapnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(90, 90, 90)
                                                    .addComponent(btTong, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(52, 52, 52)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btDocfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btThem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGap(63, 63, 63)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(btMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btXoa))
                                                    .addGap(65, 65, 65)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(btTimkiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(btXuatfile, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(136, 136, 136)
                                                    .addComponent(btAbout)
                                                    .addGap(48, 48, 48)
                                                    .addComponent(btThoat)))
                                            .addGap(0, 0, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btMacdinh)
                                    .addGap(176, 176, 176)
                                    .addComponent(btGiam)
                                    .addGap(18, 18, 18)
                                    .addComponent(btTang))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btCapnhat)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(tfMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel4)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(tfNgaynhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(13, 13, 13)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tfNgayxuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(rbCo)
                                .addComponent(rbKhong))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(rbBHYT)
                                .addComponent(rbBHXH))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btDau)
                                .addComponent(btLui)
                                .addComponent(btCuoi)
                                .addComponent(btTien)
                                .addComponent(tfSTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btThem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btDocfile))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btXoa)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btMoi))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btTimkiem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btXuatfile)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btTong)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btAbout)
                                .addComponent(btThoat))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btGiam)
                                .addComponent(btTang)
                                .addComponent(btMacdinh))))
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("BỆNH NHÂN", new javax.swing.ImageIcon(getClass().getResource("/quanlybenhvien/iconbn.png")), jPanel1); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("THÔNG TIN NHÂN VIÊN");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("BẢNG THỐNG KÊ NHÂN VIÊN");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Mã nhân viên");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Tên bệnh nhân:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Ngày ký hợp đồng:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Mức thưởng:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Giới tính:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Chức vự:");

        tfMa1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMa1KeyReleased(evt);
            }
        });

        tfTen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTen1ActionPerformed(evt);
            }
        });
        tfTen1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTen1KeyReleased(evt);
            }
        });

        tfMucthuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMucthuongKeyReleased(evt);
            }
        });

        tfNgayKHD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNgayKHDKeyReleased(evt);
            }
        });

        buttonGroup3.add(rbNam);
        rbNam.setSelected(true);
        rbNam.setText("Nam");
        rbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNamActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbNu);
        rbNu.setText("Nữ");

        btThem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btThem1.setLabel("Thêm");
        btThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThem1ActionPerformed(evt);
            }
        });

        btTimkiem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTimkiem1.setLabel("Tìm Kiếm");
        btTimkiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTimkiem1ActionPerformed(evt);
            }
        });

        btXoa1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btXoa1.setLabel("Xóa");
        btXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoa1ActionPerformed(evt);
            }
        });

        btXuatfile1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btXuatfile1.setText("Xuất file");
        btXuatfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXuatfile1ActionPerformed(evt);
            }
        });

        btMoi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btMoi1.setText("Mới");
        btMoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMoi1ActionPerformed(evt);
            }
        });

        btDocfile1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btDocfile1.setText("Đọc file");
        btDocfile1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDocfile1ActionPerformed(evt);
            }
        });

        btTong1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTong1.setText("Tổng tiền theo loại nhân viên");
        btTong1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTong1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        btDau1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btDau1.setText("Đầu");
        btDau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDau1ActionPerformed(evt);
            }
        });

        btLui1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btLui1.setText("Lùi");
        btLui1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLui1ActionPerformed(evt);
            }
        });

        btCuoi1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCuoi1.setText("Cuối");
        btCuoi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCuoi1ActionPerformed(evt);
            }
        });

        btTien1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTien1.setText("Tiến");
        btTien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTien1ActionPerformed(evt);
            }
        });

        tfSTT1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfSTT1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfSTT1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSTT1KeyReleased(evt);
            }
        });

        btAbout1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btAbout1.setText("About");
        btAbout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAbout1ActionPerformed(evt);
            }
        });

        btGiam1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btGiam1.setText("Giảm");
        btGiam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGiam1ActionPerformed(evt);
            }
        });

        btTang1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btTang1.setText("Tăng");
        btTang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTang1ActionPerformed(evt);
            }
        });

        btThoat1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btThoat1.setText("Thoát");
        btThoat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoat1ActionPerformed(evt);
            }
        });

        btCapnhat1.setText("Cập nhật");
        btCapnhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCapnhat1ActionPerformed(evt);
            }
        });

        btMacdinh1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btMacdinh1.setText("Mặc định");
        btMacdinh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMacdinh1ActionPerformed(evt);
            }
        });

        cbChucvu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Y tá", "Bác sĩ", "Phó Khoa", "Trưởng khoa" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(tfMa1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(85, 85, 85)
                                                .addComponent(btCapnhat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGap(10, 10, 10)
                                                        .addComponent(rbNam)
                                                        .addGap(38, 38, 38)
                                                        .addComponent(rbNu))
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(tfMucthuong, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(tfNgayKHD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tfTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(cbChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(btTong1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btDocfile1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(63, 63, 63)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(btMoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btXoa1))
                                                .addGap(65, 65, 65)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btTimkiem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btXuatfile1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(136, 136, 136)
                                                .addComponent(btAbout1)
                                                .addGap(48, 48, 48)
                                                .addComponent(btThoat1)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btDau1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btLui1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfSTT1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btTien1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btCuoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btMacdinh1)
                                .addGap(176, 176, 176)
                                .addComponent(btGiam1)
                                .addGap(18, 18, 18)
                                .addComponent(btTang1)
                                .addGap(201, 201, 201))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btCapnhat1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfTen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(tfMa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(tfNgayKHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMucthuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(rbNam)
                            .addComponent(rbNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbChucvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btDau1)
                            .addComponent(btLui1)
                            .addComponent(btCuoi1)
                            .addComponent(btTien1)
                            .addComponent(tfSTT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btThem1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btDocfile1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btXoa1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btMoi1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btTimkiem1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btXuatfile1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btTong1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAbout1)
                            .addComponent(btThoat1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btGiam1)
                            .addComponent(btTang1)
                            .addComponent(btMacdinh1))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("NHÂN VIÊN", new javax.swing.ImageIcon(getClass().getResource("/quanlybenhvien/iconbs.png")), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1026, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenActionPerformed

    private void rbCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCoActionPerformed

    private void btLuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLuiActionPerformed
        // TODO add your handling code here:
        if (localbn > 1) {
            localbn--;
        } else {
            localbn = 1;
        }
        HienThiBN(localbn);

    }//GEN-LAST:event_btLuiActionPerformed

    private void rbBHYTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBHYTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBHYTActionPerformed

    private void tfMaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMaKeyReleased
        CheckTTBN();
    }//GEN-LAST:event_tfMaKeyReleased

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btThoatActionPerformed

    private void btDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDauActionPerformed
        // TODO add your handling code here:
        HienThiBN(1);

    }//GEN-LAST:event_btDauActionPerformed

    private void tfMa1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMa1KeyReleased
        // TODO add your handling code here:
        CheckTTNV();
    }//GEN-LAST:event_tfMa1KeyReleased

    private void tfTen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTen1ActionPerformed

    private void btDau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDau1ActionPerformed
        // TODO add your handling code here:
         HienThiNV(1);
    }//GEN-LAST:event_btDau1ActionPerformed

    private void btLui1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLui1ActionPerformed
        // TODO add your handling code here:
        if (localnv > 1) {
            localnv--;
        } else {
            localnv = 1;
        }
        HienThiNV(localnv);
    }//GEN-LAST:event_btLui1ActionPerformed

    private void btThoat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoat1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btThoat1ActionPerformed

    private void rbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNamActionPerformed

    private void btTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTienActionPerformed
        // TODO add your handling code here:
        if (localbn < danhsachBN.getDanhSach().size() + 2) {
            localbn++;
        } else {
            localbn = danhsachBN.getDanhSach().size() + 1;
        }
        HienThiBN(localbn);

    }//GEN-LAST:event_btTienActionPerformed

    private void btCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCuoiActionPerformed
        // TODO add your handling code here:
        HienThiBN(localbn = danhsachBN.getDanhSach().size());

    }//GEN-LAST:event_btCuoiActionPerformed

    private void tfSTTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSTTKeyReleased
        // TODO add your handling code here:
        localbn = Integer.parseInt(tfSTT.getText());
        if (localbn < 1) {
            localbn = 1;
        }
        if (localbn > danhsachBN.getDanhSach().size() + 1) {
            localbn = danhsachBN.getDanhSach().size() + 1;
        }
        HienThiBN(localbn);
    }//GEN-LAST:event_tfSTTKeyReleased

    private void btMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoiActionPerformed
        // TODO add your handling code here:
        localbn = danhsachBN.getDanhSach().size() + 1;
        HienThiBN(localbn);
    }//GEN-LAST:event_btMoiActionPerformed

    private void tfSTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSTTActionPerformed

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        ThemMoiBN();
        ModeBN(modeBN);
    }//GEN-LAST:event_btThemActionPerformed

    private void tfTenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTenKeyReleased
        // TODO add your handling code here:
        CheckTTBN();
    }//GEN-LAST:event_tfTenKeyReleased

    private void tfNgaynhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNgaynhapKeyReleased
        // TODO add your handling code here:
        CheckTTBN();
    }//GEN-LAST:event_tfNgaynhapKeyReleased

    private void tfNgayxuatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNgayxuatKeyReleased
        // TODO add your handling code here:
        CheckTTBN();
    }//GEN-LAST:event_tfNgayxuatKeyReleased

    private void btCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapnhatActionPerformed
        // TODO add your handling code here:
        try {
            if (rbBHYT.isSelected()) {
                if (!danhsachBN.CapNhat(new BENHNHANBAOHIEMYTE(tfMa.getText(), tfTen.getText(),
                        new NgayThang(tfNgaynhap.getText()), new NgayThang(tfNgayxuat.getText()), rbCo.isSelected()))) {
                    int option = JOptionPane.showConfirmDialog(rootPane, "Mã chưa có tự động thêm mới không!!!");
                    if (option == 0) {
                        ThemMoiBN();
                        localbn = danhsachBN.getDanhSach().size();
                        HienThiBN(localbn);
                    } else if (option == 1) {
                        HienThiBN(localbn);
                    }
                }

            } else {
                if (!danhsachBN.CapNhat(new BENHNHANBAOHIEMXAHOI(tfMa.getText(), tfTen.getText(),
                        new NgayThang(tfNgaynhap.getText()), new NgayThang(tfNgayxuat.getText()), rbCo.isSelected()))) {
                    int option = JOptionPane.showConfirmDialog(rootPane, "Mã chưa có tự động thêm mới không!!!");
                    if (option == 0) {
                        ThemMoiBN();
                        localbn = danhsachBN.getDanhSach().size();
                        HienThiBN(localbn);
                    } else if (option == 1) {
                        HienThiBN(localbn);
                    }
                }
            }
            ModeBN(modeBN);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e,"!!!WARNING!!!",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btCapnhatActionPerformed

    private void btCapnhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCapnhat1ActionPerformed
        // TODO add your handling code here:
         try {
            
                if (!danhsachNV.CapNhat(new NHANVIEN(tfMa1.getText(), tfTen1.getText(),rbNam.isSelected(),
                        new NgayThang(tfNgayKHD.getText()), Double.parseDouble(tfMucthuong.getText()), cbChucvu.getSelectedIndex()))) {
                    int option = JOptionPane.showConfirmDialog(rootPane, "Mã chưa có tự động thêm mới không!!!");
                    if (option == 0) {
                        ThemMoiNV();
                        localnv = danhsachNV.getDanhSach().size();
                        HienThiNV(localnv);
                    } else if (option == 1) {
                        HienThiNV(localnv);
                    }
                }

            
            ModeNV(modeNV);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e,"!!!WARNING!!!",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btCapnhat1ActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        String ma="";
        ma=JOptionPane.showInputDialog(rootPane, "Nhập mã cần xóa:");
        if(!ma.equals(""))
        {
            if(!danhsachBN.Xoa(ma)) JOptionPane.showMessageDialog(rootPane, "Không có mã "+ma+" trong danh sách!!!");
            else
            {
                ModeBN(modeBN);
                HienThiBN(1);
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimkiemActionPerformed
        // TODO add your handling code here:
        String ma="";
        ma=JOptionPane.showInputDialog(rootPane, "Nhập mã cần tìm:");
        if(!ma.equals(""))
        {
            int index=danhsachBN.TimKIem(ma);
            if(index==-1) JOptionPane.showMessageDialog(rootPane, "Không có mã "+ma+" trong danh sách!!!");
            else
            {
                HienThiBN(index+1);
            }
        }
    }//GEN-LAST:event_btTimkiemActionPerformed

    private void btDocfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocfileActionPerformed
        // TODO add your handling code here:
        
            JFileChooser open =new JFileChooser();
            open.showOpenDialog(null);
            String path="";
            path=open.getSelectedFile().getPath();
            if(!path.equals("")) 
            {
                danhsachBN.readfile(path);
                ModeBN(modeBN);
            }
        
        
    }//GEN-LAST:event_btDocfileActionPerformed

    private void btXuatfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXuatfileActionPerformed
        
        
            JFileChooser open =new JFileChooser();
            open.showSaveDialog(null);
            String path="";
            path=open.getSelectedFile().getPath();
            if(!path.equals("")) danhsachBN.wirtefile(path);
       
    }//GEN-LAST:event_btXuatfileActionPerformed

    private void btMacdinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMacdinhActionPerformed
        // TODO add your handling code here:
        btMacdinh.setEnabled(false);
        btGiam.setEnabled(true);
        btTang.setEnabled(true);
        modeBN=0;
        ModeBN(modeBN);
    }//GEN-LAST:event_btMacdinhActionPerformed

    private void btGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGiamActionPerformed
        // TODO add your handling code here:
        btGiam.setEnabled(false);
        btMacdinh.setEnabled(true);
        btTang.setEnabled(true);
        modeBN=1;
        ModeBN(modeBN);
    }//GEN-LAST:event_btGiamActionPerformed

    private void btTangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTangActionPerformed
        // TODO add your handling code here:
        btTang.setEnabled(false);
        btMacdinh.setEnabled(true);
        btGiam.setEnabled(true);
        modeBN=2;
        ModeBN(modeBN);
    }//GEN-LAST:event_btTangActionPerformed

    private void btAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAboutActionPerformed
        // TODO add your handling code here:
        About();
    }//GEN-LAST:event_btAboutActionPerformed

    private void btAbout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAbout1ActionPerformed
        // TODO add your handling code here:
        About();
    }//GEN-LAST:event_btAbout1ActionPerformed

    private void btTongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTongActionPerformed
        // TODO add your handling code here:
        tong.setVisible(true);
        tong.setTable(0, danhsachBN.tongKPYU(), danhsachBN.tongPYC(), danhsachBN.tongBHYT(), danhsachBN.tongBHXH());
    }//GEN-LAST:event_btTongActionPerformed

    private void btXuatfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXuatfile1ActionPerformed
        // TODO add your handling code here:
        JFileChooser open =new JFileChooser();
            open.showSaveDialog(null);
            String path="";
            path=open.getSelectedFile().getPath();
            if(!path.equals("")) danhsachNV.wirtefile(path);
    }//GEN-LAST:event_btXuatfile1ActionPerformed

    private void tfSTT1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSTT1KeyReleased
        // TODO add your handling code here:
        localnv = Integer.parseInt(tfSTT1.getText());
        if (localnv < 1) {
            localnv = 1;
        }
        if (localnv > danhsachNV.getDanhSach().size() + 1) {
            localnv = danhsachNV.getDanhSach().size() + 1;
        }
        HienThiNV(localnv);
    }//GEN-LAST:event_tfSTT1KeyReleased

    private void btTien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTien1ActionPerformed
        // TODO add your handling code here:
        if (localnv < danhsachNV.getDanhSach().size() + 2) {
            localnv++;
        } else {
            localnv = danhsachNV.getDanhSach().size() + 1;
        }
        HienThiNV(localnv);
    }//GEN-LAST:event_btTien1ActionPerformed

    private void btCuoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCuoi1ActionPerformed
        // TODO add your handling code here:
        HienThiNV(localnv = danhsachNV.getDanhSach().size());
    }//GEN-LAST:event_btCuoi1ActionPerformed

    private void btThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThem1ActionPerformed
        // TODO add your handling code here:
        ThemMoiNV();
        ModeNV(modeNV);
    }//GEN-LAST:event_btThem1ActionPerformed

    private void btXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoa1ActionPerformed
        // TODO add your handling code here:
        String ma="";
        ma=JOptionPane.showInputDialog(rootPane, "Nhập mã cần xóa:");
        if(!ma.equals(""))
        {
            if(!danhsachNV.Xoa(ma)) JOptionPane.showMessageDialog(rootPane, "Không có mã "+ma+" trong danh sách!!!");
            else
            {
                ModeNV(modeNV);
                HienThiNV(1);
            }
        }
    }//GEN-LAST:event_btXoa1ActionPerformed

    private void btTimkiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTimkiem1ActionPerformed
        // TODO add your handling code here:
        String ma="";
        ma=JOptionPane.showInputDialog(rootPane, "Nhập mã cần tìm:");
        if(!ma.equals(""))
        {
            int index=danhsachNV.TimKIem(ma);
            if(index==-1) JOptionPane.showMessageDialog(rootPane, "Không có mã "+ma+" trong danh sách!!!");
            else
            {
                HienThiNV(index+1);
            }
        }
    }//GEN-LAST:event_btTimkiem1ActionPerformed

    private void btDocfile1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDocfile1ActionPerformed
         // TODO add your handling code here:
        JFileChooser open =new JFileChooser();
            open.showOpenDialog(null);
            String path="";
            path=open.getSelectedFile().getPath();
            if(!path.equals("")) 
            {
                danhsachNV.readfile(path);
                ModeNV(modeNV);
            }
    }//GEN-LAST:event_btDocfile1ActionPerformed

    private void btMoi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMoi1ActionPerformed
        // TODO add your handling code here:
        localnv = danhsachNV.getDanhSach().size() + 1;
        HienThiNV(localnv);
    }//GEN-LAST:event_btMoi1ActionPerformed

    private void btTong1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTong1ActionPerformed
        // TODO add your handling code here:
         tong.setVisible(true);
        tong.setTable(1, danhsachNV.tongYT(), danhsachNV.tongBS(), danhsachNV.tongPK(), danhsachNV.tongTK());
    }//GEN-LAST:event_btTong1ActionPerformed

    private void btMacdinh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMacdinh1ActionPerformed
        // TODO add your handling code here:
         btMacdinh1.setEnabled(false);
        btGiam1.setEnabled(true);
        btTang1.setEnabled(true);
        modeNV=0;
        ModeNV(modeNV);
    }//GEN-LAST:event_btMacdinh1ActionPerformed

    private void btGiam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGiam1ActionPerformed
        // TODO add your handling code here:
         btGiam1.setEnabled(false);
        btMacdinh1.setEnabled(true);
        btTang1.setEnabled(true);
        modeNV=1;
        ModeNV(modeNV);
    }//GEN-LAST:event_btGiam1ActionPerformed

    private void btTang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTang1ActionPerformed
        // TODO add your handling code here:
         btTang1.setEnabled(false);
        btMacdinh1.setEnabled(true);
        btGiam1.setEnabled(true);
        modeNV=2;
        ModeNV(modeNV);
    }//GEN-LAST:event_btTang1ActionPerformed

    private void tfTen1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTen1KeyReleased
        // TODO add your handling code here:
        CheckTTNV();
    }//GEN-LAST:event_tfTen1KeyReleased

    private void tfNgayKHDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNgayKHDKeyReleased
        // TODO add your handling code here:
        CheckTTNV();
    }//GEN-LAST:event_tfNgayKHDKeyReleased

    private void tfMucthuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMucthuongKeyReleased
        // TODO add your handling code here:
        CheckTTNV();
    }//GEN-LAST:event_tfMucthuongKeyReleased

    void HienThiBN(int index) {
        if (index == -1 || index == danhsachBN.getDanhSach().size() + 1) {
            index = danhsachBN.getDanhSach().size() + 1;
            rbBHYT.setSelected(true);
            rbKhong.setSelected(true);
            tfMa.setText("");
            tfNgaynhap.setText("");
            tfNgayxuat.setText("");
            tfTen.setText("");
            tfSTT.setText(index + "");
        } else if (index > 0 && index <= danhsachBN.getDanhSach().size()) {
            if (danhsachBN.getDanhSach().get(index - 1) instanceof BENHNHANBAOHIEMYTE) {
                rbBHYT.setSelected(true);
            } else {
                rbBHXH.setSelected(true);
            }
            if (danhsachBN.getDanhSach().get(index - 1).isPhongyeucau()) {
                rbCo.setSelected(true); 
            } else {
                rbKhong.setSelected(true);
            }
            tfMa.setText(danhsachBN.getDanhSach().get(index - 1).getMa());
            tfNgaynhap.setText(danhsachBN.getDanhSach().get(index - 1).getNgaynhap() + "");
            tfNgayxuat.setText(danhsachBN.getDanhSach().get(index - 1).getNgayxuat() + "");
            tfTen.setText(danhsachBN.getDanhSach().get(index - 1).getHoten());
            tfSTT.setText(index + "");
            localbn = index;
        }
        CheckTTBN();
    }
    void HienThiNV(int index) {
        if (index == -1 || index == danhsachNV.getDanhSach().size() + 1) {
            index = danhsachNV.getDanhSach().size() + 1;
            rbNam.setSelected(true);
            cbChucvu.setSelectedIndex(0);
            tfMa1.setText("");
            tfNgayKHD.setText("");
            tfMucthuong.setText("");
            tfTen1.setText("");
            tfSTT1.setText(index + "");
        } else if (index > 0 && index <= danhsachNV.getDanhSach().size()) {
            if (danhsachNV.getDanhSach().get(index - 1).isGioitinh()) {
                rbNam.setSelected(true);
            } else {
                rbNu.setSelected(true);
            }
            cbChucvu.setSelectedIndex(danhsachNV.getDanhSach().get(index - 1).getChucvu());
            
            tfMa1.setText(danhsachNV.getDanhSach().get(index - 1).getMa());
            tfNgayKHD.setText(danhsachNV.getDanhSach().get(index - 1).getNgaykyhopdong() + "");
            tfMucthuong.setText(danhsachNV.getDanhSach().get(index - 1).getMucthuong() + "");
            tfTen1.setText(danhsachNV.getDanhSach().get(index - 1).getHoten());
            tfSTT1.setText(index + "");
            localnv = index;
        }
        CheckTTNV();
    }
    void NapDLBN() {
        int STT = 1;
        if (danhsachBN.CheckDL() == false) {
            JOptionPane.showMessageDialog(rootPane, "Khong co du lieu!!!");
            return;
        }
        tableBN.setRowCount(0);
        for (BENHNHAN i : danhsachBN.getDanhSach()) {
            tableBN.addRow(new Object[]{STT, i.getMa(), i.getHoten(), (i.isPhongyeucau() ? "Có" : "Không"), i.getNgaynhap(),
                i.getNgayxuat(), (i instanceof BENHNHANBAOHIEMYTE ? "BHYT" : "BHXH"), i.Tinhhoadonvienphi()});
            STT++;
        }
        CheckTTBN();
    }
    void NapDLNV() {
        int STT = 1;
        if (danhsachNV.CheckDL() == false) {
            JOptionPane.showMessageDialog(rootPane, "Khong co du lieu!!!");
            return;
        }
        tableNV.setRowCount(0);
        for (NHANVIEN i : danhsachNV.getDanhSach()) {
            tableNV.addRow(new Object[]{STT, i.getMa(), i.getHoten(), (i.isGioitinh() ? "Nam" : "Nữ"), i.getNgaykyhopdong(),
                i.getMucthuong(),cbChucvu.getItemAt(i.getChucvu()), i.TinhTienLuong()});
            STT++;
        }
        CheckTTNV();
    }
    
    void CheckTTBN() {
        if (danhsachBN.CheckDL() == false) {
            btCapnhat.setEnabled(false);
            tfSTT.setEnabled(false);
            btXoa.setEnabled(false);
            btTimkiem.setEnabled(false);
            btTong.setEnabled(false);
            btDau.setEnabled(false);
            btLui.setEnabled(false);
            btTien.setEnabled(false);
            btCuoi.setEnabled(false);
            btGiam.setEnabled(false);
            btTang.setEnabled(false);
            btMacdinh.setEnabled(false);
        }
        if (localbn == 1) {
            btLui.setEnabled(false);
            btDau.setEnabled(false);
        } else {
            btLui.setEnabled(true);
            btDau.setEnabled(true);
        }
        if (localbn == danhsachBN.getDanhSach().size() || localbn == danhsachBN.getDanhSach().size() + 1) {
            btCuoi.setEnabled(false);
        } else {
            btCuoi.setEnabled(true);
        }
        if (localbn == danhsachBN.getDanhSach().size() + 1) {
            btTien.setEnabled(false);
        } else {
            btTien.setEnabled(true);
        }

        if (tfMa.getText().equals("") || tfTen.getText().equals("") || tfNgaynhap.getText().equals("")
                || tfNgayxuat.getText().equals("")) {
            btCapnhat.setEnabled(false);
            btThem.setEnabled(false);
        } else {
            if (localbn < danhsachBN.getDanhSach().size() + 1) {
                btThem.setEnabled(false);
            } else {
                btThem.setEnabled(true);
            }
            btCapnhat.setEnabled(true);
        }
        
    }
    void CheckTTNV() {
        if (danhsachNV.CheckDL() == false) {
            btCapnhat1.setEnabled(false);
            tfSTT1.setEnabled(false);
            btXoa1.setEnabled(false);
            btTimkiem1.setEnabled(false);
            btTong1.setEnabled(false);
            btDau1.setEnabled(false);
            btLui1.setEnabled(false);
            btTien1.setEnabled(false);
            btCuoi1.setEnabled(false);
            btGiam1.setEnabled(false);
            btTang1.setEnabled(false);
            btMacdinh1.setEnabled(false);
        }
        if (localnv == 1) {
            btLui1.setEnabled(false);
            btDau1.setEnabled(false);
        } else {
            btLui1.setEnabled(true);
            btDau1.setEnabled(true);
        }
        if (localnv == danhsachNV.getDanhSach().size() || localnv == danhsachNV.getDanhSach().size() + 1) {
            btCuoi1.setEnabled(false);
        } else {
            btCuoi1.setEnabled(true);
        }
        if (localnv == danhsachNV.getDanhSach().size() + 1) {
            btTien1.setEnabled(false);
        } else {
            btTien1.setEnabled(true);
        }

        if (tfMa1.getText().equals("") || tfTen1.getText().equals("") || tfNgayKHD.getText().equals("")
                || tfMucthuong.getText().equals("")) {
            btCapnhat1.setEnabled(false);
            btThem1.setEnabled(false);
        } else {
            if (localnv < danhsachNV.getDanhSach().size() + 1) {
                btThem1.setEnabled(false);
            } else {
                btThem1.setEnabled(true);
            }
            btCapnhat1.setEnabled(true);
        }
        
    }
    void ModeBN(int modeBN)
    {
        if(modeBN==0) danhsachBN.SapXepMacDinh();
        else if(modeBN==1) danhsachBN.SapXepGiam();
        else if(modeBN==2) danhsachBN.SapXepTang();
        NapDLBN();
        CheckTTBN();
    }
    void ModeNV(int modeNV)
    {
        if(modeNV==0) danhsachNV.SapXepMacDinh();
        else if(modeNV==1) danhsachNV.SapXepGiam();
        else if(modeNV==2) danhsachNV.SapXepTang();
        NapDLNV();
        CheckTTNV();
    }
    void ThemMoiBN() {
        try {
            if (rbBHYT.isSelected()) {
                if (!danhsachBN.ThemMoi(new BENHNHANBAOHIEMYTE(tfMa.getText(), tfTen.getText(),
                        new NgayThang(tfNgaynhap.getText()), new NgayThang(tfNgayxuat.getText()), rbCo.isSelected()))) {
                    JOptionPane.showMessageDialog(rootPane, "Mã đã có!!!");
                }

            } else {
                if (!danhsachBN.ThemMoi(new BENHNHANBAOHIEMXAHOI(tfMa.getText(), tfTen.getText(),
                        new NgayThang(tfNgaynhap.getText()), new NgayThang(tfNgayxuat.getText()), rbCo.isSelected()))) {
                    JOptionPane.showMessageDialog(rootPane, "Mã đã có!!!");
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e,"!!!WARNING!!!",JOptionPane.WARNING_MESSAGE);
        }

    }
    void ThemMoiNV() {
        try {
            
                if (!danhsachNV.ThemMoi(new NHANVIEN(tfMa1.getText(), tfTen1.getText(),rbNam.isSelected(),
                        new NgayThang(tfNgayKHD.getText()), Double.parseDouble(tfMucthuong.getText()), cbChucvu.getSelectedIndex()))) {
                    JOptionPane.showMessageDialog(rootPane, "Mã đã có!!!");
                }

            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e,"!!!WARNING!!!",JOptionPane.WARNING_MESSAGE);
        }

    }
    void About()
    {
        JOptionPane.showMessageDialog(rootPane, "QUẢN LÝ BỆNH VIỆN\nBùi Anh Trúc\nCS311");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppBenhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppBenhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppBenhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppBenhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new FormDangNhap().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAbout;
    private javax.swing.JButton btAbout1;
    private javax.swing.JButton btCapnhat;
    private javax.swing.JButton btCapnhat1;
    private javax.swing.JButton btCuoi;
    private javax.swing.JButton btCuoi1;
    private javax.swing.JButton btDau;
    private javax.swing.JButton btDau1;
    private javax.swing.JButton btDocfile;
    private javax.swing.JButton btDocfile1;
    private javax.swing.JButton btGiam;
    private javax.swing.JButton btGiam1;
    private javax.swing.JButton btLui;
    private javax.swing.JButton btLui1;
    private javax.swing.JButton btMacdinh;
    private javax.swing.JButton btMacdinh1;
    private javax.swing.JButton btMoi;
    private javax.swing.JButton btMoi1;
    private javax.swing.JButton btTang;
    private javax.swing.JButton btTang1;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThem1;
    private javax.swing.JButton btThoat;
    private javax.swing.JButton btThoat1;
    private javax.swing.JButton btTien;
    private javax.swing.JButton btTien1;
    private javax.swing.JButton btTimkiem;
    private javax.swing.JButton btTimkiem1;
    private javax.swing.JButton btTong;
    private javax.swing.JButton btTong1;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton btXoa1;
    private javax.swing.JButton btXuatfile;
    private javax.swing.JButton btXuatfile1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbChucvu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbBHXH;
    private javax.swing.JRadioButton rbBHYT;
    private javax.swing.JRadioButton rbCo;
    private javax.swing.JRadioButton rbKhong;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNu;
    private javax.swing.JTextField tfMa;
    private javax.swing.JTextField tfMa1;
    private javax.swing.JTextField tfMucthuong;
    private javax.swing.JTextField tfNgayKHD;
    private javax.swing.JTextField tfNgaynhap;
    private javax.swing.JTextField tfNgayxuat;
    private javax.swing.JTextField tfSTT;
    private javax.swing.JTextField tfSTT1;
    private javax.swing.JTextField tfTen;
    private javax.swing.JTextField tfTen1;
    // End of variables declaration//GEN-END:variables
}
