/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlybenhvien;

import javax.swing.JOptionPane;

/**
 *
 * @author trucn
 */
public class FormDangNhap extends javax.swing.JFrame {
    DSTaiKhoan danhsachtk=new DSTaiKhoan();
    private boolean dangnhap;
    /**
     * Creates new form FormDangNhap
     */
    public FormDangNhap() {
        initComponents();
        CheckTT();
        danhsachtk.readfile("TK.txt");
        dangnhap=false;
    }

    public boolean isDangnhap() {
        return dangnhap;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTaikhoan = new javax.swing.JTextField();
        btDangnhap = new javax.swing.JButton();
        btQuenmatkhau = new javax.swing.JButton();
        pfMatkhau = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfTaikhoan1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pfMatkhau1 = new javax.swing.JPasswordField();
        btDangky = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pfMatkhau2 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ BỆNH VIỆN");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên tài khoản:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu:");

        tfTaikhoan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTaikhoan.setText("admin");
        tfTaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTaikhoanActionPerformed(evt);
            }
        });
        tfTaikhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTaikhoanKeyReleased(evt);
            }
        });

        btDangnhap.setText("Đăng nhập");
        btDangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangnhapActionPerformed(evt);
            }
        });

        btQuenmatkhau.setText("Quên mật khẩu");
        btQuenmatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuenmatkhauActionPerformed(evt);
            }
        });

        pfMatkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfMatkhau.setText("admin");
        pfMatkhau.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pfMatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfMatkhauActionPerformed(evt);
            }
        });
        pfMatkhau.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfMatkhauKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btDangnhap)
                        .addGap(18, 18, 18)
                        .addComponent(btQuenmatkhau))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pfMatkhau, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(tfTaikhoan, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfTaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pfMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDangnhap)
                    .addComponent(btQuenmatkhau))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đăng nhập", jPanel1);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên tài khoản:");

        tfTaikhoan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfTaikhoan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTaikhoan1ActionPerformed(evt);
            }
        });
        tfTaikhoan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfTaikhoan1KeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mật khẩu:");

        pfMatkhau1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfMatkhau1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfMatkhau1ActionPerformed(evt);
            }
        });
        pfMatkhau1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfMatkhau1KeyReleased(evt);
            }
        });

        btDangky.setText("Đăng ký");
        btDangky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDangkyActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nhập lại mật khẩu:");

        pfMatkhau2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pfMatkhau2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfMatkhau2ActionPerformed(evt);
            }
        });
        pfMatkhau2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pfMatkhau2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btDangky, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pfMatkhau1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(tfTaikhoan1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pfMatkhau2))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTaikhoan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pfMatkhau1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pfMatkhau2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btDangky)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Đăng ký", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pfMatkhauKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfMatkhauKeyReleased
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_pfMatkhauKeyReleased

    private void pfMatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfMatkhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfMatkhauActionPerformed

    private void tfTaikhoanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTaikhoanKeyReleased
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_tfTaikhoanKeyReleased

    private void tfTaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTaikhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTaikhoanActionPerformed

    private void pfMatkhau2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfMatkhau2KeyReleased
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_pfMatkhau2KeyReleased

    private void pfMatkhau2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfMatkhau2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfMatkhau2ActionPerformed

    private void pfMatkhau1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pfMatkhau1KeyReleased
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_pfMatkhau1KeyReleased

    private void pfMatkhau1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfMatkhau1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfMatkhau1ActionPerformed

    private void tfTaikhoan1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTaikhoan1KeyReleased
        // TODO add your handling code here:
        CheckTT();
    }//GEN-LAST:event_tfTaikhoan1KeyReleased

    private void tfTaikhoan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTaikhoan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTaikhoan1ActionPerformed

    private void btDangkyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangkyActionPerformed
        // TODO add your handling code here:
        if(pfMatkhau1.getText().equals(pfMatkhau2.getText()))
        {
            if(danhsachtk.ThemMoi(new TaiKhoan(tfTaikhoan1.getText(),pfMatkhau1.getText())))
            {            
                danhsachtk.wirtefile("TK.txt");
            }
            else JOptionPane.showMessageDialog(rootPane, "Tài khoản đã tồn tại!!!");
        }
        else JOptionPane.showMessageDialog(rootPane, "Mật khẩu không khớp!!!");
    }//GEN-LAST:event_btDangkyActionPerformed

    private void btQuenmatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuenmatkhauActionPerformed
        // TODO add your handling code here:
        String ma="";
        ma=JOptionPane.showInputDialog(rootPane, "Nhập tên tài khoản cần tìm:");
        if(!ma.equals(""))
        {
            int index=danhsachtk.TimKIem(ma);
            if(index==-1) JOptionPane.showMessageDialog(rootPane, "Tài khoản "+ma+" không tồn tại!!!");
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Tài khoản:"+danhsachtk.getDanhSach().get(index).getTentk()
                        +"\nMật khẩu:"+danhsachtk.getDanhSach().get(index).getMatkhau());
            }
        }
    }//GEN-LAST:event_btQuenmatkhauActionPerformed

    private void btDangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDangnhapActionPerformed
        // TODO add your handling code here:
        String ma="";
        ma=tfTaikhoan.getText();
        int index=danhsachtk.TimKIem(ma);
        if(index==-1) JOptionPane.showMessageDialog(rootPane, "Tài khoản "+ma+" không tồn tại!!!");
        else
        {
            if(pfMatkhau.getText().equals(danhsachtk.getDanhSach().get(index).getMatkhau()))
            {
                dangnhap=true;
                this.dispose();
                new AppBenhVien().setVisible(true);
            }
            else JOptionPane.showMessageDialog(rootPane, "Tài khoản hoặc mật khẩu sai!!!");        
        }
    }//GEN-LAST:event_btDangnhapActionPerformed
    void CheckTT()
    {
        if(tfTaikhoan.getText().equals("")||pfMatkhau.getText().equals(""))
        {
            btDangnhap.setEnabled(false);
        }
        else btDangnhap.setEnabled(true);
        if(tfTaikhoan1.getText().equals("")||pfMatkhau1.getText().equals("")||pfMatkhau2.getText().equals(""))
        {
            btDangky.setEnabled(false);
        }
        else btDangky.setEnabled(true);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDangky;
    private javax.swing.JButton btDangnhap;
    private javax.swing.JButton btQuenmatkhau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPasswordField pfMatkhau;
    private javax.swing.JPasswordField pfMatkhau1;
    private javax.swing.JPasswordField pfMatkhau2;
    private javax.swing.JTextField tfTaikhoan;
    private javax.swing.JTextField tfTaikhoan1;
    // End of variables declaration//GEN-END:variables
}
